// src/pages/cardapio/index.tsx
import { Fab } from "@mui/material"
import ArrowBackIcon from '@mui/icons-material/ArrowBack';

const Cardapio = () => {
    return (
        <>
            <Fab
                size="small"
                color="primary"
                sx={{
                    position: 'fixed',
                    top: 20,
                    left: 20,
                }}
                onClick={() => window.location.href = '/'}
            >
                <ArrowBackIcon sx={{ color: "background.default" }} />
            </Fab>
            <div>
                {/* <iframe loading="lazy" style={{ position: 'absolute', width: '100%', height: '100%', top: 0, left: 0, border: 'none', padding: 0, margin: 0 }}
                    src="https://www.canva.com/design/DAGbdhINMFk/Ha0j9By6XjF-umx0_ucFAA/view?embed" allowFullScreen allow="fullscreen">
                </iframe> */}
                <iframe loading="lazy" style={{ position: 'absolute', width: '100%', height: '100%', top: 0, left: 0, border: 'none', padding: 0, margin: 0 }}
                    src="https://www.canva.com/design/DAGJDxmYhRM/UU5aDvYuP6GYHP9FUQkSCQ/view?embed" allowFullScreen allow="fullscreen">
                </iframe>
            </div>
        </>
    )
}

export default Cardapio

// app/pages/cardapio.vue
<script setup lang="ts">
definePageMeta({
  layout: 'cardapio'
})

const loaded = ref(false)
const iframeRef = ref<HTMLIFrameElement | null>(null)
</script>

<template>
  <div
    class="w-full bg-stone-900 flex justify-center relative"
    style="height: 100svh; padding: 3rem 1rem 1rem;"
  >
    <USkeleton
      v-if="!loaded"
      class="absolute w-full max-w-3xl rounded-lg"
      style="top: 3rem; bottom: 1rem; left: 50%; transform: translateX(-50%);"
    />

    <iframe
      ref="iframeRef"
      loading="lazy"
      class="w-full max-w-3xl rounded-lg transition-opacity duration-300"
      :class="loaded ? 'opacity-100' : 'opacity-0'"
      style="height: 100%; border: none; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16);"
      src="https://www.canva.com/design/DAGyopGCjLc/yBInJ25nigDwMw0uWRBlQg/view?embed"
      allowfullscreen
      allow="fullscreen"
      @load="loaded = true"
    />
  </div>
</template>
